//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRC_Scouting_V2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool clickToEmptyTextBoxes {
            get {
                return ((bool)(this["clickToEmptyTextBoxes"]));
            }
            set {
                this["clickToEmptyTextBoxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Anonymous")]
        public string username {
            get {
                return ((string)(this["username"]));
            }
            set {
                this["username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool minimizeHomeWentEventLoads {
            get {
                return ((bool)(this["minimizeHomeWentEventLoads"]));
            }
            set {
                this["minimizeHomeWentEventLoads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool firstTimeLoad {
            get {
                return ((bool)(this["firstTimeLoad"]));
            }
            set {
                this["firstTimeLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50.87.144.85")]
        public string mySqlDatabaseIP {
            get {
                return ((string)(this["mySqlDatabaseIP"]));
            }
            set {
                this["mySqlDatabaseIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string mySqlDatabasePort {
            get {
                return ((string)(this["mySqlDatabasePort"]));
            }
            set {
                this["mySqlDatabasePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xnovax_testers")]
        public string mySqlDatabaseUsername {
            get {
                return ((string)(this["mySqlDatabaseUsername"]));
            }
            set {
                this["mySqlDatabaseUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ErcM2zrlEHkcxMd5e6G2hA==")]
        public string mySqlDatabasePassword {
            get {
                return ((string)(this["mySqlDatabasePassword"]));
            }
            set {
                this["mySqlDatabasePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xnovax_robotics")]
        public string mySqlDatabaseName {
            get {
                return ((string)(this["mySqlDatabaseName"]));
            }
            set {
                this["mySqlDatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool clearConsoleOnToggle {
            get {
                return ((bool)(this["clearConsoleOnToggle"]));
            }
            set {
                this["clearConsoleOnToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool allowExportToTextFile {
            get {
                return ((bool)(this["allowExportToTextFile"]));
            }
            set {
                this["allowExportToTextFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showQuestionButtons {
            get {
                return ((bool)(this["showQuestionButtons"]));
            }
            set {
                this["showQuestionButtons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool colourTeamComparisonStatistics {
            get {
                return ((bool)(this["colourTeamComparisonStatistics"]));
            }
            set {
                this["colourTeamComparisonStatistics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color teamComparisonEqualValueColour {
            get {
                return ((global::System.Drawing.Color)(this["teamComparisonEqualValueColour"]));
            }
            set {
                this["teamComparisonEqualValueColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50.87.144.85")]
        public string sqlDatabaseIP {
            get {
                return ((string)(this["sqlDatabaseIP"]));
            }
            set {
                this["sqlDatabaseIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string sqlDatabasePort {
            get {
                return ((string)(this["sqlDatabasePort"]));
            }
            set {
                this["sqlDatabasePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xnovax_testers")]
        public string sqlDatabaseUsername {
            get {
                return ((string)(this["sqlDatabaseUsername"]));
            }
            set {
                this["sqlDatabaseUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ErcM2zrlEHkcxMd5e6G2hA==")]
        public string sqlDatabasePassword {
            get {
                return ((string)(this["sqlDatabasePassword"]));
            }
            set {
                this["sqlDatabasePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xnovax_robotics")]
        public string sqlDatabaseName {
            get {
                return ((string)(this["sqlDatabaseName"]));
            }
            set {
                this["sqlDatabaseName"] = value;
            }
        }
    }
}
